# Generated by Django 5.2.12 on 2026-03-13 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCache",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("price", models.DecimalField(decimal_places=6, max_digits=18)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="instruments.instrument"),
                ),
            ],
        ),
    ]
