# Generated by Django 5.2.12 on 2026-03-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Instrument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("isin", models.CharField(max_length=12, unique=True)),
                ("ticker", models.CharField(blank=True, max_length=20, null=True)),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(max_length=3)),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Stock"),
                            ("ETF", "Etf"),
                            ("BOND", "Bond"),
                            ("FUND", "Fund"),
                            ("OTHER", "Other"),
                        ],
                        default="STOCK",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
