# Generated by Django 5.2.12 on 2026-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="ticker",
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
