# Generated by Django 5.2.12 on 2026-03-13 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("instruments", "0001_initial"),
        ("portfolios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="portfolios", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="holding",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="holdings", to="portfolios.portfolio"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="instrument",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="instruments.instrument"),
        ),
        migrations.AddField(
            model_name="transaction",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="transactions", to="portfolios.portfolio"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("user", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="holding",
            unique_together={("portfolio", "instrument")},
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={("portfolio", "broker_reference")},
        ),
    ]
