# Generated by Django 5.2.12 on 2026-03-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instruments", "0002_alter_instrument_ticker"),
        ("portfolios", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["portfolio", "-date"], name="portfolios__portfol_f4fd6e_idx"),
        ),
        migrations.AddConstraint(
            model_name="holding",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="holding_quantity_non_negative"
            ),
        ),
    ]
