# Generated by Django 5.2.12 on 2026-03-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("brokers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokerconnection",
            name="broker_type",
            field=models.CharField(
                choices=[
                    ("degiro", "Degiro"),
                    ("trade_republic", "Trade Republic"),
                    ("interactive_brokers", "Interactive Brokers"),
                    ("bitpanda", "Bitpanda"),
                ],
                max_length=20,
            ),
        ),
    ]
