from __future__ import annotations

from .models import SuggestedETF

# ── Sector ETF Catalogue ─────────────────────────────────

SECTOR_ETF_MAP: dict[str, list[SuggestedETF]] = {
    "Technology": [
        SuggestedETF(
            name="iShares S&P 500 Info Tech Sector UCITS ETF",
            ticker="IUIT.L",
            isin="IE00B3WJKG14",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Information Technology",
            why="Low-cost US tech exposure with 70+ holdings",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Information Technology UCITS ETF",
            ticker="XDWT.DE",
            isin="IE00BM67HT60",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Information Technology",
            why="Global tech exposure across developed markets",
        ),
        SuggestedETF(
            name="Amundi MSCI World Information Technology UCITS ETF",
            ticker="WTEC.PA",
            isin="LU1681046931",
            provider="Amundi",
            ter="0.35%",
            index_tracked="MSCI World Information Technology",
            why="Euronext-listed alternative for European investors",
        ),
    ],
    "Healthcare": [
        SuggestedETF(
            name="iShares STOXX Europe 600 Health Care UCITS ETF",
            ticker="SXDPEX.DE",
            isin="DE000A0Q4R36",
            provider="iShares",
            ter="0.46%",
            index_tracked="STOXX Europe 600 Health Care",
            why="Broad European healthcare, 53 holdings, UCITS compliant",
        ),
        SuggestedETF(
            name="iShares S&P 500 Health Care Sector UCITS ETF",
            ticker="IUHC.L",
            isin="IE00B43HR379",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Health Care",
            why="US-focused healthcare with lower TER, includes JNJ, UNH, Pfizer",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Health Care UCITS ETF",
            ticker="XDWH.DE",
            isin="IE00BM67HK77",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Health Care",
            why="Global healthcare exposure across developed markets",
        ),
    ],
    "Financial Services": [
        SuggestedETF(
            name="iShares S&P 500 Financials Sector UCITS ETF",
            ticker="IUFS.L",
            isin="IE00B4JNQZ49",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Financials",
            why="US financials including banks, insurance, diversified financials",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Financials UCITS ETF",
            ticker="XDWF.DE",
            isin="IE00BM67HL84",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Financials",
            why="Global financial sector exposure across developed markets",
        ),
        SuggestedETF(
            name="Amundi STOXX Europe 600 Banks UCITS ETF",
            ticker="BNKE.PA",
            isin="LU1834983477",
            provider="Amundi",
            ter="0.30%",
            index_tracked="STOXX Europe 600 Banks",
            why="European banking sector focus",
        ),
    ],
    "Consumer Cyclical": [
        SuggestedETF(
            name="iShares S&P 500 Consumer Discretionary Sector UCITS ETF",
            ticker="IUCD.L",
            isin="IE00B4MCHD36",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Consumer Discretionary",
            why="US consumer discretionary including Amazon, Tesla, Home Depot",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Consumer Discretionary UCITS ETF",
            ticker="XDWC.DE",
            isin="IE00BM67HP23",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Consumer Discretionary",
            why="Global consumer discretionary exposure",
        ),
    ],
    "Communication Services": [
        SuggestedETF(
            name="iShares S&P 500 Communication Services Sector UCITS ETF",
            ticker="IUCM.L",
            isin="IE00BDDRF700",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Communication Services",
            why="US communication services including Alphabet, Meta, Netflix",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Communication Services UCITS ETF",
            ticker="XDWM.DE",
            isin="IE00BM67HR47",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Communication Services",
            why="Global communication services exposure",
        ),
    ],
    "Industrials": [
        SuggestedETF(
            name="iShares S&P 500 Industrials Sector UCITS ETF",
            ticker="IUIS.L",
            isin="IE00B4LN9N13",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Industrials",
            why="US industrials including aerospace, defense, machinery",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Industrials UCITS ETF",
            ticker="XDWI.DE",
            isin="IE00BM67HV82",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Industrials",
            why="Global industrials exposure across developed markets",
        ),
        SuggestedETF(
            name="Amundi STOXX Europe 600 Industrial Goods UCITS ETF",
            ticker="STIP.PA",
            isin="LU1834987890",
            provider="Amundi",
            ter="0.30%",
            index_tracked="STOXX Europe 600 Industrial Goods & Services",
            why="European industrials focus",
        ),
    ],
    "Consumer Defensive": [
        SuggestedETF(
            name="iShares S&P 500 Consumer Staples Sector UCITS ETF",
            ticker="IUCS.L",
            isin="IE00B40B8R38",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Consumer Staples",
            why="Recession-resistant consumer brands (P&G, Coca-Cola, Walmart)",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Consumer Staples UCITS ETF",
            ticker="XDWS.DE",
            isin="IE00BM67HN09",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Consumer Staples",
            why="Global consumer staples exposure",
        ),
    ],
    "Energy": [
        SuggestedETF(
            name="iShares S&P 500 Energy Sector UCITS ETF",
            ticker="IUES.L",
            isin="IE00B4KBBD01",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Energy",
            why="US energy sector including Exxon, Chevron",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Energy UCITS ETF",
            ticker="XDWE.DE",
            isin="IE00BM67HM91",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Energy",
            why="Global energy exposure across developed markets",
        ),
        SuggestedETF(
            name="iShares STOXX Europe 600 Oil & Gas UCITS ETF",
            ticker="SXEPEX.DE",
            isin="DE000A0H08M3",
            provider="iShares",
            ter="0.46%",
            index_tracked="STOXX Europe 600 Oil & Gas",
            why="European-focused oil and gas exposure",
        ),
    ],
    "Utilities": [
        SuggestedETF(
            name="iShares S&P 500 Utilities Sector UCITS ETF",
            ticker="IUUS.L",
            isin="IE00B4KBBD01",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Utilities",
            why="Stable cash flows, regulated revenues, low beta",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Utilities UCITS ETF",
            ticker="XDWU.DE",
            isin="IE00BM67HR47",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Utilities",
            why="Global utilities exposure",
        ),
    ],
    "Real Estate": [
        SuggestedETF(
            name="iShares Developed Markets Property Yield UCITS ETF",
            ticker="IWDP.L",
            isin="IE00B1FZS350",
            provider="iShares",
            ter="0.59%",
            index_tracked="FTSE EPRA/NAREIT Developed Dividend+",
            why="Global developed markets real estate with dividend focus",
        ),
        SuggestedETF(
            name="Xtrackers FTSE EPRA/NAREIT Developed Europe UCITS ETF",
            ticker="XDER.DE",
            isin="LU0489337690",
            provider="Xtrackers",
            ter="0.33%",
            index_tracked="FTSE EPRA/NAREIT Developed Europe",
            why="European real estate focus with lower TER",
        ),
    ],
    "Basic Materials": [
        SuggestedETF(
            name="iShares S&P 500 Materials Sector UCITS ETF",
            ticker="IUMS.L",
            isin="IE00B4MKCJ84",
            provider="iShares",
            ter="0.15%",
            index_tracked="S&P 500 Materials",
            why="US materials sector including chemicals, metals, packaging",
        ),
        SuggestedETF(
            name="Xtrackers MSCI World Materials UCITS ETF",
            ticker="XDWP.DE",
            isin="IE00BM67HS53",
            provider="Xtrackers",
            ter="0.25%",
            index_tracked="MSCI World Materials",
            why="Global materials exposure across developed markets",
        ),
    ],
}

# ── Region ETF Catalogue ─────────────────────────────────

REGION_ETF_MAP: dict[str, list[SuggestedETF]] = {
    "North America": [
        SuggestedETF(
            name="iShares Core S&P 500 UCITS ETF",
            ticker="CSPX.L",
            isin="IE00B5BMR087",
            provider="iShares",
            ter="0.07%",
            index_tracked="S&P 500",
            why="Ultra-low-cost core US equity exposure",
        ),
        SuggestedETF(
            name="Vanguard S&P 500 UCITS ETF",
            ticker="VUSA.L",
            isin="IE00B3XXRP09",
            provider="Vanguard",
            ter="0.07%",
            index_tracked="S&P 500",
            why="Distributing version for income-focused investors",
        ),
        SuggestedETF(
            name="Xtrackers S&P 500 UCITS ETF",
            ticker="XSPX.DE",
            isin="IE00BM67HT60",
            provider="Xtrackers",
            ter="0.06%",
            index_tracked="S&P 500",
            why="Lowest TER S&P 500 tracker available on Xetra",
        ),
    ],
    "Europe": [
        SuggestedETF(
            name="iShares Core MSCI Europe UCITS ETF",
            ticker="SMEA.L",
            isin="IE00B4K48X80",
            provider="iShares",
            ter="0.12%",
            index_tracked="MSCI Europe",
            why="Broad European equity exposure across 15 countries",
        ),
        SuggestedETF(
            name="Vanguard FTSE Developed Europe UCITS ETF",
            ticker="VEUR.L",
            isin="IE00B945VN12",
            provider="Vanguard",
            ter="0.10%",
            index_tracked="FTSE Developed Europe",
            why="Lowest-cost broad European equity tracker",
        ),
        SuggestedETF(
            name="Xtrackers MSCI Europe UCITS ETF",
            ticker="XMEU.DE",
            isin="LU0274209237",
            provider="Xtrackers",
            ter="0.12%",
            index_tracked="MSCI Europe",
            why="Xetra-listed European equity tracker",
        ),
    ],
    "Asia Pacific": [
        SuggestedETF(
            name="iShares Core MSCI Pacific ex Japan UCITS ETF",
            ticker="CPXJ.L",
            isin="IE00B52MJY50",
            provider="iShares",
            ter="0.20%",
            index_tracked="MSCI Pacific ex Japan",
            why="Australia, Hong Kong, Singapore, New Zealand exposure",
        ),
        SuggestedETF(
            name="Vanguard FTSE Japan UCITS ETF",
            ticker="VJPN.L",
            isin="IE00B95PGT31",
            provider="Vanguard",
            ter="0.15%",
            index_tracked="FTSE Japan",
            why="Low-cost Japanese equity exposure",
        ),
        SuggestedETF(
            name="Xtrackers MSCI Japan UCITS ETF",
            ticker="XMJP.DE",
            isin="LU0274209740",
            provider="Xtrackers",
            ter="0.12%",
            index_tracked="MSCI Japan",
            why="Xetra-listed Japanese equity tracker",
        ),
    ],
    "Emerging Markets": [
        SuggestedETF(
            name="iShares Core MSCI EM IMI UCITS ETF",
            ticker="EIMI.L",
            isin="IE00BKM4GZ66",
            provider="iShares",
            ter="0.18%",
            index_tracked="MSCI Emerging Markets IMI",
            why="Broadest EM coverage including small caps",
        ),
        SuggestedETF(
            name="Vanguard FTSE Emerging Markets UCITS ETF",
            ticker="VFEM.L",
            isin="IE00B3VVMM84",
            provider="Vanguard",
            ter="0.22%",
            index_tracked="FTSE Emerging Markets",
            why="Distributing EM tracker for income investors",
        ),
        SuggestedETF(
            name="Xtrackers MSCI Emerging Markets UCITS ETF",
            ticker="XMME.DE",
            isin="IE00BTJRMP35",
            provider="Xtrackers",
            ter="0.18%",
            index_tracked="MSCI Emerging Markets",
            why="Xetra-listed EM tracker",
        ),
    ],
}

# ── Bond ETF Catalogue ───────────────────────────────────

BOND_ETFS: list[SuggestedETF] = [
    SuggestedETF(
        name="iShares Core Euro Government Bond UCITS ETF",
        ticker="IEGA.DE",
        isin="IE00B4WXJJ64",
        provider="iShares",
        ter="0.09%",
        index_tracked="Bloomberg Euro Treasury Bond",
        why="Core eurozone government bond exposure, intermediate duration",
    ),
    SuggestedETF(
        name="iShares Core Euro Corporate Bond UCITS ETF",
        ticker="IEAC.DE",
        isin="IE00B3F81R35",
        provider="iShares",
        ter="0.20%",
        index_tracked="Bloomberg Euro Corporate Bond",
        why="Investment-grade euro corporate bonds",
    ),
    SuggestedETF(
        name="Vanguard EUR Eurozone Government Bond UCITS ETF",
        ticker="VETY.DE",
        isin="IE00BH04GL39",
        provider="Vanguard",
        ter="0.07%",
        index_tracked="Bloomberg Euro Government Float Adjusted Bond",
        why="Lowest-cost eurozone government bond tracker",
    ),
]

# ── Global Equity ETF Catalogue ──────────────────────────

GLOBAL_EQUITY_ETFS: list[SuggestedETF] = [
    SuggestedETF(
        name="iShares Core MSCI World UCITS ETF",
        ticker="IWDA.L",
        isin="IE00B4L5Y983",
        provider="iShares",
        ter="0.20%",
        index_tracked="MSCI World",
        why="Core developed markets equity, 1,500+ holdings",
    ),
    SuggestedETF(
        name="Vanguard FTSE All-World UCITS ETF",
        ticker="VWRL.L",
        isin="IE00B3RBWM25",
        provider="Vanguard",
        ter="0.22%",
        index_tracked="FTSE All-World",
        why="Broadest single-ETF global equity exposure including EM",
    ),
    SuggestedETF(
        name="Xtrackers MSCI World UCITS ETF",
        ticker="XDWD.DE",
        isin="IE00BJ0KDQ92",
        provider="Xtrackers",
        ter="0.19%",
        index_tracked="MSCI World",
        why="Xetra-listed global developed markets tracker",
    ),
]

# ── Dividend ETF Catalogue ───────────────────────────────

DIVIDEND_ETFS: list[SuggestedETF] = [
    SuggestedETF(
        name="Vanguard FTSE All-World High Dividend Yield UCITS ETF",
        ticker="VHYL.L",
        isin="IE00B8GKDB10",
        provider="Vanguard",
        ter="0.29%",
        index_tracked="FTSE All-World High Dividend Yield",
        why="Global high-yield equities, ~3.5% trailing yield",
    ),
    SuggestedETF(
        name="iShares STOXX Global Select Dividend 100 UCITS ETF",
        ticker="ISPA.DE",
        isin="DE000A0F5UH1",
        provider="iShares",
        ter="0.46%",
        index_tracked="STOXX Global Select Dividend 100",
        why="Top 100 dividend payers globally, ~4.5% yield",
    ),
    SuggestedETF(
        name="SPDR S&P Euro Dividend Aristocrats UCITS ETF",
        ticker="EUDV.DE",
        isin="IE00B5M1WJ87",
        provider="SPDR",
        ter="0.30%",
        index_tracked="S&P Euro High Yield Dividend Aristocrats",
        why="European companies with stable/growing dividends, ~3.0% yield",
    ),
]

# ── Defensive ETF Catalogue ──────────────────────────────

DEFENSIVE_ETFS: list[SuggestedETF] = [
    SuggestedETF(
        name="iShares Edge MSCI World Minimum Volatility UCITS ETF",
        ticker="MVOL.L",
        isin="IE00B8FHGS14",
        provider="iShares",
        ter="0.30%",
        index_tracked="MSCI World Minimum Volatility",
        why="Systematic low-volatility strategy across 300+ global stocks",
    ),
    SuggestedETF(
        name="iShares S&P 500 Consumer Staples Sector UCITS ETF",
        ticker="IUCS.L",
        isin="IE00B40B8R38",
        provider="iShares",
        ter="0.15%",
        index_tracked="S&P 500 Consumer Staples",
        why="Recession-resistant consumer brands (P&G, Coca-Cola, Walmart)",
    ),
    SuggestedETF(
        name="iShares S&P 500 Utilities Sector UCITS ETF",
        ticker="IUUS.L",
        isin="IE00B4KBBD01",
        provider="iShares",
        ter="0.15%",
        index_tracked="S&P 500 Utilities",
        why="Stable cash flows, regulated revenues, low beta",
    ),
]

# ── Low-Correlation ETF Catalogue ────────────────────────

CORRELATION_ETFS: list[SuggestedETF] = [
    SuggestedETF(
        name="iShares Physical Gold ETC",
        ticker="IGLN.L",
        isin="IE00B4ND3602",
        provider="iShares",
        ter="0.12%",
        index_tracked="LBMA Gold Price",
        why="Gold historically has near-zero correlation with equities",
    ),
    SuggestedETF(
        name="iShares Core Euro Government Bond UCITS ETF",
        ticker="IEGA.DE",
        isin="IE00B4WXJJ64",
        provider="iShares",
        ter="0.09%",
        index_tracked="Bloomberg Euro Treasury Bond",
        why="Government bonds provide ballast during equity sell-offs",
    ),
    SuggestedETF(
        name="iShares Developed Markets Property Yield UCITS ETF",
        ticker="IWDP.L",
        isin="IE00B1FZS350",
        provider="iShares",
        ter="0.59%",
        index_tracked="FTSE EPRA/NAREIT Developed Dividend+",
        why="Real estate returns have moderate equity correlation (~0.5)",
    ),
]
